name: 'upyun-upx-action'
description: 'Deploy your files to upyun using upyun-upx.'
author: 'YaoKun <yaokun@bwcxtech.com>'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: 'blue'
  icon: 'upload-cloud'